#!/usr/sbin/env ruby
require 'json'
require 'erubis'

showoff_json = JSON.parse(File.read('showoff.json'))
sections = showoff_json['sections'].map { |s| s.values.first }
other_dirs = %w[_files _images _preshow]
preso_dirs = (sections + other_dirs).sort

template = Erubis::Eruby.new(DATA.read)
locals = { preso_dirs: preso_dirs,
           year: Time.now.year,
           author: showoff_json['author']
         }

outfile = File.new('LICENSE', 'w')
outfile.write(template.result(locals))
outfile.close

__END__
Copyright (c) <%= year -%> <%= author -%>

The presentation content in this repository — files in the following
directories:

<% preso_dirs.each do |dir| %>
*  `<%= dir -%>`
<% end %>

is licensed under the Creative Commons Attribution-NonCommercial 4.0
International License. To view a copy of this license, visit
http://creativecommons.org/licenses/by-nc/4.0/.

Software in this repository — all other files — is licensed under the MIT
License. See below.

MIT License
==============================================================================

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
